name: FCIShop
version: 1.0
author: Filip Zocktan & HappyHappyBoy
main: de.teamfci.fcishop.FCIShop
depends: [FCIDataprovider]
commands:
  fcis:
    description: Zeigt Plugininfo an/shopverwaltung.